### ISSUE TITLE
USER STORY: Header Mobile + Desktop, Navbar Desktop, Footer Mobile + Desktop

### ISSUE THREAD

**Issue by RickofManc** [RickofManc/fresh-casts#1]
As a Site User, I can understand what the site aim is and my options from viewing the homepage, so that I can intuitively navigate the site and enjoy the content

---

### Acceptance Criteria:

* Acceptance Criteria 1: The site structure and layout should be clear and simple to navigate - all features within 1-2 clicks
* Acceptance Criteria 2: Site Users should be able to change the displayed posts by clicking on a category within the Main Menu
* Acceptance Criteria 3: Site Users will have an option to Sign Up, In or Out from the homepage 

### Tasks:

- [x] Header with site name for desktop and mobile
- [x] Option to explore site through main menu button; Useful Links, About Us, Contact Us, Accessibility Statement, User Agreement, Copyright Info
- [x] Option to sign-up/in/out accessible through fixed Navbar button
- [x] Footer for Desktop and Mobile
- [x] Homepage content by default will be displayed in latest ascending order
