### ISSUE TITLE
USER STORY: Site User - Sign-Out Modal

### ISSUE THREAD

**Issue by RickofManc** [RickofManc/fresh-casts#10]
As a Site User, I can be asked to confirm my request to sign-out, so that I can cancel if requested in error

---

### Acceptance Criteria:

* Acceptance Criteria 1: Site Users will be able to sign-out from clicking a link in the Header, Main Menu or Footer
* Acceptance Criteria 2: Site Users will be asked to confirm they would like to proceed to sign-out
* Acceptance Criteria 3: If Site Users confirm they would like to sign-out they will lose access to features i.e. ability to post and comment

### Tasks:

- [x] Create a link in the Header called 'Sign-out'
- [x] The link will be visible only when a Site User is signed in
- [x] When clicked, Site Users will be asked to confirm they would like to sign-out
- [x] Create route to return Site User to homepage without access to features when the sing-out button is clicked
