### ISSUE TITLE
USER STORY: Site User - Liking Posts

### ISSUE THREAD

**Issue by RickofManc** [RickofManc/fresh-casts#12]
As a Site User, I can 'like' a post, so that I can provide positive feedback to the blogger

---

### Acceptance Criteria:

* Acceptance Criteria 1: A Site User that has signed in to their account will be able to click a Heart icon within a post to inform the blogger of they like the post
* Acceptance Criteria 2: If the icon has been clicked in error, Site Users should be able to deselect the icon to remove the like
* Acceptance Criteria 3: Site Users should only be able to deselect a Like where they have initially added one

### Tasks:

- [x] Create a function that enables an interactive Heart icon to receive clicks to enable a 'Like'
- [x] The functionality should be a toggle to allow Site Users to remove their Like if clicked in error
- [x] A rule needs to exist that permits Like deselection only where a Site User has added a Like
- [x] The Heart icon should change from an outline to filled when clicked
