### ISSUE TITLE
USER STORY: Site User - Commenting

### ISSUE THREAD

**Issue by RickofManc** [RickofManc/fresh-casts#13]
As a Site User, I can add comments to a post, so that I can provide feedback and/or start a discussion

---

### Acceptance Criteria:

* Acceptance Criteria 1: A Site User that has signed in to their account will be able to add a comment to a post, providing their opinion on the shared post
* Acceptance Criteria 2: A button clearly stating to 'Submit' their comment will be available next to the open text box
* Acceptance Criteria 3: User will be informed the comment will be reviewed and approved in due course

### Tasks:

- [x] Create a blank text box to be displayed underneath a post. This will only be available when the post has been expanded into its own page
- [x] Signed-in Site Users will be able to click within the area to start typing a comment
- [x] A 'Submit' button will be displayed underneath the text box ready for the Site User to click and post their comment
