### ISSUE TITLE
USER STORY: Site User - Create Posts

### ISSUE THREAD

**Issue by RickofManc** [RickofManc/fresh-casts#16]
As a Site User, I can create a post, so that I can share shows I like with others

---

### Acceptance Criteria:

* Acceptance Criteria 1: A Site User that has signed into their account will have the option to share a podcast they like through creating a post
* Acceptance Criteria 2: An option within the Main Menu or User Account page will redirect Sites Users to a page displaying a Form
* Acceptance Criteria 3: Site Users will be asked to complete the Form that will come with placeholder information to support the data entry
* Acceptance Criteria 4: On submitting the Form, Site Admin will be asked to approve the post before publishing it on the site

### Tasks:

- [x] Using the existing functionality for Site Admin to add posts, recreate this for Site Users in a new HTML page
- [x] A link to this page will be displayed as a feature within the Users Profile page
- [x] When navigating to this page, Sites Users will complete a Form that enables them to add; Podcast Title, Podcast Category, Podcast By, Podcast Date, Posted By (their username), Post date (automatically provided), Brief description of the show, URL to the show - this should also pull the shows profile image, Site Users Review
- [x] When navigating to this page, Sites Users will complete a Form that enables them to add; Podcast Title, Podcast Category, Podcast By, Podcast Date, Posted By (their username), Brief description of the show, URL to the show, Show image, Site Users Review
