### ISSUE TITLE
USER STORY: Site Admin - Approve new posts

### ISSUE THREAD

**Issue by RickofManc** [RickofManc/fresh-casts#17]
As Site Admin, I can approve new posts from Site Users, so that I can manage site content
---

### Acceptance Criteria:

* Acceptance Criteria 1: Site Admin will receive an email requesting them to approve a new post
* Acceptance Criteria 2: The email will request Site Admin signs-in to the Admin portal to view the draft and publish the post

### Tasks:

- [x] Create a function for Site Admin to be emailed with any new post request Forms
- [x] Site Admin will log into the Admin Portal, navigate to the Form and be asked to Publish the post
- [ ] Site User receives an automatic email from Site Admin confirming the decision and the next steps to view their published post

**Comment by RickofManc** [comment]
Functionality to approve new posts is working correctly from the Admin panel, however an email notification is not being recieved. This is being raised as a bug
