### ISSUE TITLE
USER STORY: About Us Page

### ISSUE THREAD

**Issue by RickofManc** [RickofManc/fresh-casts#19]
As Site Owner, I would like to provide Site Users with more information on the sites creation, so that Site Users can understand the aims and potentially contribute to ideas and development

---

### Acceptance Criteria:

* Acceptance Criteria 1: Site Users will be able to access this page from either the Main Menu or Footer
* Acceptance Criteria 2: Site Users will be navigated to a new page which informs of who, when, why and what Fresh Casts is about
* Acceptance Criteria 3: Site Users should intuitively return back to the homepage from either clicking the logo in the Header or from a text link on the page
* Acceptance Criteria 4: Site Users will be offered an opportunity to register an account following understanding more about Fresh Casts

### Tasks:

- [x] Create a HTML page that provide information on who, when, why and what Fresh Casts is about
- [x] Add a link to the page within the Main Menu and Footer
- [x] Within the About Us page, add a link to the Sign-up page to promote a growing community
