### ISSUE TITLE
USER STORY: Website Responsiveness for Mobile, Tablet and Desktop devices

### ISSUE THREAD

**Issue by RickofManc** [RickofManc/fresh-casts#2]
As a Site User, I can access the site on differing devices, so I can interact with content on my preferred device

---

### Acceptance Criteria:

* Acceptance Criteria 1: Successful tests for Responsiveness using Developer Tools
* Acceptance Criteria 2: Successful tests for Responsiveness through User Testing

### Tasks:

- [x] Header with site name and strapline for desktop (fixed) and mobile (not fixed)
- [x] Option to explore site through main menu button; Useful Links, About Us, Contact Us, Accessibility Statement, User Agreement, Copyright Info
- [x] Navbar disappears with vertical user scroll on mobile devices to maximise screen content
- [x] Option to sign-up/in/out accessible through fixed Navbar button
- [x] Fixed Footer for Desktop and Mobile
- [x] Homepage content by default will be displayed in latest ascending order

**Comment by RickofManc** [comment]
Testing complete for a browser, device and accessibility position. See test results within repo for more details.
