### ISSUE TITLE
USER STORY: Contact Us Page

### ISSUE THREAD

**Issue by RickofManc** [RickofManc/fresh-casts#20]
As Site Owner, I can provide a contact form for Site Users, so they can provide feedback, request features, report offensive posts, comments, user or to request the deletion of their own posts

---

### Acceptance Criteria:

* Acceptance Criteria 1: Site Users will be able to access this page from either the Main Menu or Footer
* Acceptance Criteria 2: Site Users will be introduced to the FAQ page in case they hadn't already viewed this information and could of had their question answered
* Acceptance Criteria 3: Site Users will be provided with a Form to complete, learning where the Form is sent and when to expect a response
* Acceptance Criteria 4: Site Users should intuitively return back to the homepage from either clicking the logo in the Header or from a text link on the page
* Acceptance Criteria 5: Site Users will receive an email confirming the Form has been submitted

### Tasks:

- [x] Create a HTML page that provides a Form users complete when wanting to make contact
- [x] Form will require the Site Users Username, Email Address
- [x] Provide placeholders on the Form where required, and indicate a potential response time
- [x] Add a link to the page within the Main Menu
- [x] Create database table to receive submitted forms
- [ ] Notify Site Admin when a Form has been submitted
- [ ] Send confirmation to Site User of the Form being submitted
- [x] Build functionality and statuses to allow Site Admin to manage the Forms i.e. Open, Responded, Complete
