### ISSUE TITLE
USER STORY: FAQ Page

### ISSUE THREAD

**Issue by RickofManc** [RickofManc/fresh-casts#21]
As a Site User, I can find answers to general questions, so that I don't have to wait for a response from the Site Owner

---

### Acceptance Criteria:

* Acceptance Criteria 1: Site Users most popular questions can be answered in a single page that is conveniently accessed from the Main Menu or Footer
* Acceptance Criteria 2: Site Users will be provided with a link to contact Site Admin if a question cannot be answered

### Tasks:

- [ ] Create a HTML page for FAQs
- [ ] Link page to Main Menu and Footer
- [ ] Use an accordion style for FAQs
- [ ] Try to limit number of questions conventionally i.e. 15
- [ ] Provide a link to the Contact Us page in case a Site Users question cannot be answered
