### ISSUE TITLE
USER STORY: Accessibility Statement

### ISSUE THREAD

**Issue by RickofManc** [RickofManc/fresh-casts#23]
As a Site User, I can find out how the Site Owner has made content accessible, so that I can interact as designed

---

### Acceptance Criteria:

* Acceptance Criteria 1: Site Users will be able to learn how Fresh Casts care about accessibility and about them, plus provide information about the accessibility of our content
* Acceptance Criteria 2: Clicking the Main Menu or Footer link will navigate Site Users to a page that displays the Accessibility statement
*

### Tasks:

- [x] Create a HTML page for Accessibility Statement
- [x] Link page to the Main Menu and Footer
- [x] Within the page display text
