### ISSUE TITLE
USER STORY: User Agreement

### ISSUE THREAD

**Issue by RickofManc** [RickofManc/fresh-casts#24]
As a Site User, I can learn the responsibilities for site use, so that I can act responsibly

---

### Acceptance Criteria:

* Acceptance Criteria 1: Site Users will be able to learn how Fresh Casts asks them to act whilst posting and commenting on the site, and also the responsibilities of Site Admin with complaints
* Acceptance Criteria 2: Clicking the Main Menu or Footer link will navigate Site Users to a page that displays the User Agreement

### Tasks:

- [x] Create a HTML page for User Agreement
- [x] Link page to the Main Menu and Footer
- [x] Within the page display text

**Comment by RickofManc** [comment]
Page testing complete, see testing files within repo for results.
