### ISSUE TITLE
USER STORY: Copyright Statement

### ISSUE THREAD

**Issue by RickofManc** [RickofManc/fresh-casts#25]
As a Site User, I can learn about the Copyright aspects of this site, so that I do not infringe on copyright rules

---

### Acceptance Criteria:

* Acceptance Criteria 1: Site Users will be able to learn about the Copyright use for Fresh Casts by clicking on a link within the Main Menu and Footer
* Acceptance Criteria 2: Clicking the link will navigate Site Users to a page that displays the Copyright statement

### Tasks:

- [x] Create a HTML page for Copyright Statement
- [x] Link page to the Main Menu and Footer
- [x] Within the page display text

**Comment by RickofManc** [comment]
Page testing complete, see testing files within repo for results.
