### ISSUE TITLE
USER STORY: Fresh Casts Logo

### ISSUE THREAD

**Issue by RickofManc** [RickofManc/fresh-casts#28]
As Site Owner, I want a Fresh Casts logo, so Site Users can identify with the site

---

### Acceptance Criteria:

* Acceptance Criteria 1: A logo that is identifiable as relating to podcasts that can help build the brand
* Acceptance Criteria 2: Logo to be used within the Header, Footer and any external comms i.e. email service

### Tasks:

- [x] Research competitor and conventional branding for podcast sharing and streaming sites
- [x] Adopt high contrast colour scheme to viewed by all Site Users
- [x] Create different sizes to be used appropriately for differing media queries

**Comment by RickofManc** [comment]
User story delivered. Logo is available offline line in differing sizes and styles.
