### ISSUE TITLE
USER STORY: Site Admin - Create, Read, Update & Delete Posts and Comments

### ISSUE THREAD

**Issue by RickofManc** [RickofManc/fresh-casts#3]
As a Site Admin I can create, read, update and delete posts so that I can manage Fresh Casts content

---

### Acceptance Criteria:

* Acceptance Criteria 1: Site Admin can Create, Read, Update and Delete Posts
* Acceptance Criteria 2: Site Admin can Create, Read, Update and Delete Comments

### Tasks:

- [x] Develop functionality for all features - see also US16, US12, US13 for tasks
- [x] Create Super User account
- [x] Create views required for each feature
- [x] Use object-oriented programming
- [x] Test each feature from a Site Admin profile
- [x] Create dummy Site User account to support testing
