### ISSUE TITLE
USER STORY: Site User - Update Own Comment

### ISSUE THREAD

**Issue by RickofManc** [RickofManc/fresh-casts#32]
As a Site User, I can update my own comments, so that I can manage my content

---

### Acceptance Criteria:

* Acceptance Criteria 1: A signed-in Site User will have an clickable link next to their comments to 'Edit'. When clicked the comment text box will open with the Site User being able to Edit
* Acceptance Criteria 2: A 'Save' button/link will be displayed when the text box is open that can be clicked once the Site User has finished making updates

### Tasks:

- [ ] Create Update functionality that enables a text box to be editable by the user who has made the comment
- [ ] Function should be linked to the buttons for Edit and Save to allow the user to close the text box when updates are complete
- [ ] Test through differing dummy Site User accounts to ensure this feature is limited to own comments and not other users

**Comment by RickofManc** [comment]
Due to time constraints to reach the MVP date this feature will be delayed to the next release.
