### ISSUE TITLE
USER STORY: Sign-in Modal

### ISSUE THREAD

**Issue by RickofManc** [RickofManc/fresh-casts#34]
As Site Owner, I can prompt visitors to join the community, so the number of contributors increases and in turn posts and comments increase creating a community 

---

### Acceptance Criteria:

* Acceptance Criteria 1: Timed test that after a non-registered Site User has browsed for 60 seconds, a modal opens promoting the benefits of having a user account
* Acceptance Criteria 2: A button within the modal should redirect the Site User to the Sign-Up page
* Acceptance Criteria 3: A button within the modal should allow users to decline the opportunity
* Acceptance Criteria 4: The modal should not reappear again during the same browser session

### Tasks:

- [ ] Utilise Bootstrap modal to create a simple and inviting message to users, listing 3 main benefits of having a user account
- [ ] Add a button to the modal to redirect users to the Sign-Up page
- [ ] Add a button to allow users to close the modal and return to their current page
- [ ] Modal should display after 60 seconds, and not reappear during that browsing session or for that IP address - no badgering users

**Comment by RickofManc** [comment]
A strategic decision has been taken not to develop this feature as it would have a detrimental impact on the user experience.
