### ISSUE TITLE
USER STORY: Site User - Recent Activity

### ISSUE THREAD

**Issue by RickofManc** [RickofManc/fresh-casts#35]
As a Site User, I can view my recent activity, so that I can learn behaviour traits i.e. which podcast categories I like most, where I have posted comments etc.

---

### Acceptance Criteria:

* Acceptance Criteria 1: Site Users profile page has an additional section that provides an overview of recent activity

### Tasks:

- [ ] Within the User Profile page, create a second section for Recent Activity
- [ ] Data to be collated to support User Posts, Comments and Likes from across the site
- [ ] If possible data should be chart based, and interactive allowing Site Users to click on data to navigate to where it was input i.e. click on a comment and be taken to the post where the comment is located
