### ISSUE TITLE
USER STORY: Homepage content

### ISSUE THREAD

**Issue by RickofManc** [RickofManc/fresh-casts#4]
As a Site User, I can view a list of posts, so that I can easily select a post to view

---

### Acceptance Criteria:

* Acceptance Criteria 1: By default the Homepage will displayed the most recent posts first
* Acceptance Criteria 2: A small card with the post title, strapline and image will be displayed
* Acceptance Criteria 3: Site Users will be able to click any part of the card to expand the post in another page
* Acceptance Criteria 4: Site Users will be able to return back to the Homepage results via a text link on the page, or by clicking the site logo with the Header (however this will reset the view)

### Tasks:

- [x] Order homepage posts by most recent first
- [x] Create small clickable card for post title, strapline and image
- [x] Create card view to display all post details on a new page
- [x] Create option for Site Users to return back to the Homepage search results
- [x] Create option for Site Users to navigate back to the Homepage from clicking the site logo
