### ISSUE TITLE
USER STORY: Homepage Post (short description)

### ISSUE THREAD

**Issue by RickofManc** [RickofManc/fresh-casts#5]
As a Site User, I have sufficient post details on the homepage, so that I can choose whether to click and find out more
---

### Acceptance Criteria:

* Acceptance Criteria 1: Successful user test resulting in users instinctively clicking on the cards to find out further information, and in a later release play a podcast

### Tasks:

- [x] Create a card for the homepage which details the podcast title, strapline, post category, and an image from the podcast show
- [x] Set image to left of text
- [x] Provide Site Users with an active link for 'More details' which when clicked will navigate to view the full description and comments in a new page
- [x] Display the number of comments and likes next to icons within the card
- [x] Separate cards on the homepage by a light coloured horizontal line
