### ISSUE TITLE
USER STORY: Expanded Post (full description)

### ISSUE THREAD

**Issue by RickofManc** [RickofManc/fresh-casts#6]
As a Site User, I can click on a homepage post to see more details including comments, so that I can understand if this is a podcast I would like to hear

---

### Acceptance Criteria:

* Acceptance Criteria 1: Site Users can view all details posted by the blogger
* Acceptance Criteria 2: Comments can be viewed below the post
* Acceptance Criteria 3: Site Users can add Comments
* Acceptance Criteria 4: Site Users can add a Like
* Acceptance Criteria 5: Site Users can share the post on social media
* Acceptance Criteria 6: Site Users can return back to the Homepage

### Tasks:

- [x] Create a card for which details the podcast title, strapline, post category, user who posted, date created, date posted, podcast description, user review and an image from the podcast show
- [x] Set larger image to the above of the text
- [x] Display the comments below the text, with a button to toggle them into view
- [x] Provide a Heart icon for Site Users to click to register their like for the post
- [x] Display the number of likes next to the relevant icons within the card
- [x] Provide Site Users with a text link to return back to the homepage
