### ISSUE TITLE
USER STORY: Search Content - Desktop & Mobile

### ISSUE THREAD

**Issue by RickofManc** [RickofManc/fresh-casts#7]
As a Site User, I can search for content by entering descriptive words, so that I can filter the content to my liking

---

### Acceptance Criteria:

* Acceptance Criteria 1: Search functionality is accessible to Site Users on the desktop Homepage
* Acceptance Criteria 2: Search functionality is accessible to Site Users within the Main Menu to aid mobile users

### Tasks:

- [ ] Develop search functionality
- [ ] Create an icon and text field box for the Site User to type keywords
- [ ] Limit the length of text field to conventional 50 characters
- [ ] Provide information or an example to the Site User on what to type
- [ ] Create a link to the search function from the Main Menu

**Comment by RickofManc** [comment]
Due to time constraints to reach the MVP date this feature will be delayed to the next release.
