### ISSUE TITLE
USER STORY: Site User - Sign Up Page

### ISSUE THREAD

**Issue by RickofManc** [RickofManc/fresh-casts#8]
As a Site User, I can register an account, so that I can comment and like posts

---

### Acceptance Criteria:

* Acceptance Criteria 1: Site Users are provided with a simple Form to complete in order to register an account
* Acceptance Criteria 2: Form fields should follow convention for sign-up forms
* Acceptance Criteria 3: Form buttons should enable the Form to be submitted or cancelled
* Acceptance Criteria 4: Placeholders within Form fields will support Site Users with inputting the requested data

### Tasks:

- [x] Create HTML page for users to Sign-Up
- [x] Following fields will be required; Name, Email Address, Username, Password, Confirm Password
- [x] Create a Submit and Cancel button for under the above fields
- [x] Link the Form with the database
- [x] Test as Dummy Site User
