### ISSUE TITLE
USER STORY: Site User - Sign-In Page

### ISSUE THREAD

**Issue by RickofManc** [RickofManc/fresh-casts#9]
As a Site User, I can sign-in to my account, so that I can add comments and likes to posts

---

### Acceptance Criteria:

* Acceptance Criteria 1: Site Users will be able to sign-in from clicking a link in the Header, Main Menu or Footer
* Acceptance Criteria 2: Sites Users will be required to enter their Username and Password to activate their profile and Fresh Casts features
* Acceptance Criteria 3: A message should confirm to Site Users when they have successfully signed in
* Acceptance Criteria 4: A message should inform Site Users if the information entered was not valid, and to try again
* Acceptance Criteria 5: Site Users will be able to change profile information including their password

### Tasks:

- [x] Create HTML page for users to Sign-In
- [x] Following Form fields will be required; Username, Password
- [x] Create Submit and Reset buttons for the Form
- [x] Add placeholders within the fields to support the users journey
- [x] Display a message confirming that sign-in has been successful
- [x] Display an error message if the data input was invalid
- [x] Provide an Edit Profile page where user can self serve changes to key account details
- [x] Link the Form with the database
- [x] Test as Dummy Site User
